version: '2'

services:
    esp20_zookeeper:
        image: wurstmeister/zookeeper
        container_name: esp20_zookeeper
        ports:
        - "2181:2181"
        expose:
        - "2181"
        networks:
                app_subnet:
                        ipv4_address: 10.10.1.2
    esp20_kafka:
        image: wurstmeister/kafka
        container_name: esp20_kafka
        ports:
          - "9092:9092"
        expose:
          - "9902"
        environment:
                KAFKA_ADVERTISED_HOST_NAME: 10.10.1.3
                KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.10.1.3:9092
                KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on:
          - esp20_zookeeper
        volumes:
          - ./:/etc/kafka
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
                app_subnet:
                        ipv4_address: 10.10.1.3
    
    esp20_db:
        image: mysql:5.6
        container_name: esp20_db
        volumes:
          - db_data:/var/lib/mysql
        restart: always
        ports:
                - 3307:3307
        expose: 
                - 3307
        environment:
                MYSQL_ROOT_PASSWORD: password
                MYSQL_DATABASE: dubaidash
                MYSQL_USER: demo_user
                MYSQL_PASSWORD: demo_user
        networks:
                app_subnet:
                        ipv4_address: 10.10.1.4

networks:
    app_subnet: 
        ipam:
            driver: default
            config:
              - subnet: 10.10.1.0/24
                gateway: 10.10.1.1

volumes:
        db_data:
