version: '2'

services:
        esp20_zookeeper:
                image: wurstmeister/zookeeper
                container_name: esp20_zookeeper
                ports:
                        - "20001:2181"
                expose:
                        - "20001"
                networks:
                        dubaidash_subnet:
                                ipv4_address: 10.10.1.2

        esp20_kafka:
                image: wurstmeister/kafka
                container_name: esp20_kafka
                ports:
                        - "20002:9092"
                expose:
                        - "20002"
                environment:
                        KAFKA_ADVERTISED_HOST_NAME: 10.10.1.3
                        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.10.1.3:9092
                        KAFKA_ZOOKEEPER_CONNECT: esp20_zookeeper:2181
                        KAFKA_RESERVED_BROKER_MAX_ID: 1001
                        KAFKA_BROKER_ID: 1001
                        KAFKA_CREATE_TOPICS: "states:1:1"
                depends_on:
                        - esp20_zookeeper
                volumes:
                        - ./:/etc/kafka
                        - /var/run/docker.sock:/var/run/docker.sock
                networks:
                        dubaidash_subnet:
                                ipv4_address: 10.10.1.3
   
        esp20_dubaidash:
                image: 192.168.160.48:5000/esp20_dubaidash:latest
                container_name: esp20_dubaidash
                ports: 
                        - "20003:8080"
                expose:
                        - "20003" 
                depends_on: 
                        - esp20_kafka
                        - esp20_logstash
                networks:
                        dubaidash_subnet:
                                ipv4_address: 10.10.1.5

        esp20_dubaidashapi:
                image: 192.168.160.48:5000/esp20_dubaidashapi:latest
                container_name: esp20_dubaidashapi
                ports:
                        - "20004:8080"
                expose:
                        - "20004"
                environment:
                        - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.160.87:20006/dubaidash?user=pilot&password=plane
                        - SPRING_DATASOURCE_USERNAME=pilot
                        - SPRING_DATASOURCE_PASSWORD=plane
                        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
                depends_on: 
                        - esp20_kafka
                        - esp20_db
                        - esp20_logstash
                links:
                        - esp20_logstash:esp20_logstash
                networks:
                        dubaidash_subnet:
                                ipv4_address: 10.10.1.6  
        
        esp20_react:
                image: 192.168.160.48:5000/esp20_react:latest
                container_name: esp20_react
                depends_on:
                        - esp20_dubaidashapi
                volumes: 
                        - '.:/app'
                        - '/app/node_modules'
                ports:
                        - "20005:3000"
                environment:
                        - CHOKIDAR_USEPOLLING=true
                networks:
                        dubaidash_subnet:
                                ipv4_address: 10.10.1.7
        esp20_db:
                image: mysql:5.6
                container_name: esp20_db
                command: --default-authentication-plugin=mysql_native_password
                volumes:
                        - db_data:/var/lib/mysql
                        - ./initDB:/docker-entrypoint-initdb.d
                restart: always
                ports:
                        - "20006:3306"
                expose: 
                        - "20006"
                environment:
                        MYSQL_ROOT_PASSWORD: 'password'
                        MYSQL_DATABASE: 'dubaidash'
                        MYSQL_USER: 'pilot'
                        MYSQL_PASSWORD: 'plane'
                volumes:
                        - ./initDB:/docker-entrypoint-initdb.d
                networks:
                        dubaidash_subnet:
                                ipv4_address: 10.10.1.4
        esp20_logstash:
                build:
                        context: logstash/
                container_name: esp20_logstash
                volumes:
                        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
                        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
                ports:                                                                                
                        - "5000:5000"
                        - "20007:20007/tcp"
                networks:
                        dubaidash_subnet:
                                ipv4_address: 10.10.1.8

networks:
        dubaidash_subnet: 
                ipam:
                        driver: default
                        config:
                                - subnet: 10.10.1.0/24
                                  gateway: 10.10.1.1

volumes:
        db_data:
