pipeline {
    agent any
    tools {
        jdk 'jdk11'
    }
    stages {
        
        stage('test1'){
            steps{
                sh 'pwd'
                sh 'ls'
                sh 'mvn --version'
                sh 'java -version'
                sh 'docker --version'
            }
        }
        stage('Cloning repository') {
            steps {
                git(
                    branch: 'master',
                    url: 'https://github.com/DubaiDash-ES/code.git'
                )
                sh "chmod +x -R ${env.WORKSPACE}"
            }
        }
        
        stage('Testing'){
            steps{
                sh './jenkins/scripts/tests.sh'
            }
        }
        
        stage('Build') {
            
            steps {
                sh 'ls'
                sh './jenkins/scripts/build.sh'
            }
        }
        
        /*
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deploy.sh'
            }
        }*/
    }
}
